# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.bicLogLik <- function(argY, argTheta, argPii, argSigma, argIndex) {
    .Call('_knnfuse6_bicLogLik', PACKAGE = 'knnfuse6', argY, argTheta, argPii, argSigma, argIndex)
}

.myEm <- function(argY, argGraphtype, argm, argTheta, argSigma, argPii, argArbSigma, argM, argIndex, argMaxAdmm, argMaxNR, argCk, argA, argPenalty, argLambdaVals, argEpsilon, argDelta, argMaxRep, argVerbose, argDynamic) {
    .Call('_knnfuse6_myEm', PACKAGE = 'knnfuse6', argY, argGraphtype, argm, argTheta, argSigma, argPii, argArbSigma, argM, argIndex, argMaxAdmm, argMaxNR, argCk, argA, argPenalty, argLambdaVals, argEpsilon, argDelta, argMaxRep, argVerbose, argDynamic)
}

.myEm2 <- function(argY, argnu, argGraphtype, argm, argTheta, argSigma, argPii, argArbSigma, argM, argIndex, argMaxAdmm, argMaxNR, argCk, argA, argPenalty, argLambdaVals, argEpsilon, argDelta, argMaxRep, argVerbose, argDynamic) {
    .Call('_knnfuse6_myEm2', PACKAGE = 'knnfuse6', argY, argnu, argGraphtype, argm, argTheta, argSigma, argPii, argArbSigma, argM, argIndex, argMaxAdmm, argMaxNR, argCk, argA, argPenalty, argLambdaVals, argEpsilon, argDelta, argMaxRep, argVerbose, argDynamic)
}

