# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.bicLogLik <- function(argY, argTheta, argPii, argSigma, argIndex) {
    .Call('_GFuse_bicLogLik', PACKAGE = 'GFuse', argY, argTheta, argPii, argSigma, argIndex)
}

.myEm <- function(argY, argGraphtype, argm, argTheta, argSigma, argPii, argArbSigma, argM, argIndex, argMaxAdmm, argMaxNR, argCk, argA, argPenalty, argLambdaVals, argEpsilon, argDelta, argMaxRep, argVerbose, argDynamic) {
    .Call('_GFuse_myEm', PACKAGE = 'GFuse', argY, argGraphtype, argm, argTheta, argSigma, argPii, argArbSigma, argM, argIndex, argMaxAdmm, argMaxNR, argCk, argA, argPenalty, argLambdaVals, argEpsilon, argDelta, argMaxRep, argVerbose, argDynamic)
}

.myEm2 <- function(argY, argnu, argGraphtype, argm, argTheta, argSigma, argPii, argArbSigma, argM, argIndex, argMaxAdmm, argMaxNR, argCk, argA, argPenalty, argLambdaVals, argEpsilon, argDelta, argMaxRep, argVerbose, argDynamic) {
    .Call('_GFuse_myEm2', PACKAGE = 'GFuse', argY, argnu, argGraphtype, argm, argTheta, argSigma, argPii, argArbSigma, argM, argIndex, argMaxAdmm, argMaxNR, argCk, argA, argPenalty, argLambdaVals, argEpsilon, argDelta, argMaxRep, argVerbose, argDynamic)
}

